version: 2.1

commands:
  app_setup:
    description: "Get the app ready to test"
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

executors:
  app_executor:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m

jobs:
  build:
    executor: app_executor
    steps:
      - app_setup
      - run:
          name: Build
          command: ./gradlew assemble
  lint:
    executor: app_executor
    steps:
      - app_setup
      - run:
          name: Run Lint
          command: ./gradlew lint
      - store_artifacts:
          path: app/build/reports
          destination: reports
  test:
    executor: app_executor
    steps:
      - app_setup
      - run:
          name: Run Tests
          command: ./gradlew test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/reports
          destination: reports

workflows:
  version: 2.1
  build_lint_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build